# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_confirmed', models.ManyToManyField(to='events.Event')),
            ],
        ),
    ]
