# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160830_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='eventsVolunteering',
            new_name='events_volunteering',
        ),
    ]
