# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160831_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_to', to='events.Event'),
        ),
    ]
