# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
