# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_estemated_interrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='honor_event',
            field=models.BooleanField(default=False),
        ),
    ]
